### ISSUE TITLE
Text Bug on Migrate page

### ISSUE THREAD

**Issue by muhammedea** [Ubeswap/ubeswap-interface-v3#7]
On migrate page, when showing the current price there is a text bug
<img width="830" alt="Screenshot 2024-10-12 at 16 10 17" src="https://github.com/user-attachments/assets/952cd256-aa79-472e-b8af-d96a156e5f8f">

**Comment by eben619** [comment]
Could you provide more infomation on this? @muhammedea

**Comment by muhammedea** [comment]
@eben619  I have updated the description

**Comment by eben619** [comment]
@muhammedea nice, thanks.
